name: Publish EnvironmentZCompat Datapack for 1.20.1

on:
  release:
    types: [published]

jobs:
  publish:
    # Only run if the release is from branch 1.20.1
    if: ${{ github.event.release.target_commitish == '1.20.1' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Package EnvironmentZCompat Datapack
        run: |
          zip -r environmentz-compats.zip EnvironmentZCompat

      - name: Publish to Modrinth
        env:
          MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
          MODRINTH_PROJECT_ID: ${{ secrets.MODRINTH_PROJECT_ID }}
          VERSION: ${{ github.event.release.tag_name }}
          CHANGELOG: ${{ github.event.release.body }}
        run: |
          echo "Publishing version ${VERSION} for 1.20.1..."
          curl -X POST "https://api.modrinth.com/api/v1/version" \
            -H "Authorization: Bearer ${MODRINTH_API_KEY}" \
            -F "project_id=${MODRINTH_PROJECT_ID}" \
            -F "version_number=${VERSION}" \
            -F "version_type=release" \
            -F "changelog=${CHANGELOG}" \
            -F "game_versions[]=1.20.1" \
            -F "loaders[]=datapack" \
            -F "files[]=@environmentz-compats.zip"
