name: Create Release Zip
permissions:
  contents: write

on:
  push:
    tags:
      - '*.*.*'  # Matches tags like 1.0.0, 1.0.1, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository at the pushed tag.
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # 2. Zip only the contents of the EnvironmentZCompat folder.
      #    The working-directory ensures that only files inside EnvironmentZCompat are included.
      - name: Zip EnvironmentZCompat folder contents
        working-directory: EnvironmentZCompat
        run: |
          rm -f ../environmentz-compat.zip
          zip -r ../environmentz-compat.zip *

      # 3. Check if a release already exists for this tag.
      - name: Check if release exists
        id: check_release
        uses: actions/github-script@v6
        with:
          script: |
            const tag = process.env.TAG_NAME;
            try {
              const release = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: tag,
              });
              core.info(`Release for tag ${tag} already exists.`);
              core.setOutput("upload_url", release.data.upload_url);
            } catch (error) {
              if (error.status === 404) {
                core.info(`No release for tag ${tag} found.`);
                core.setOutput("upload_url", "");
              } else {
                throw error;
              }
            }
        env:
          TAG_NAME: ${{ github.ref_name }}

      # 4. If no release exists, create one.
      - name: Create GitHub Release if not exists
        id: create_release
        if: steps.check_release.outputs.upload_url == ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      # 5. Set the final upload URL (from the existing release or from the newly created one).
      - name: Set final upload url
        id: set_upload_url
        run: |
          if [ "${{ steps.check_release.outputs.upload_url }}" != "" ]; then
            echo "Using existing release upload URL: ${{ steps.check_release.outputs.upload_url }}"
            echo "upload_url=${{ steps.check_release.outputs.upload_url }}" >> $GITHUB_OUTPUT
          else
            echo "Using new release upload URL: ${{ steps.create_release.outputs.upload_url }}"
            echo "upload_url=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_OUTPUT
          fi

      # 6. Upload the generated zip file as a release asset.
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
          asset_path: environmentz-compat.zip
          asset_name: environmentz-compat.zip
          asset_content_type: application/zip
