name: Create Release Zip

on:
  push:
    tags:
      - '*.*.*'  # Matches tags like 1.0.0, 1.0.1, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository at the pushed tag
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # Zip only the contents of the EnvironmentZCompat folder.
      # The working-directory parameter ensures only files inside EnvironmentZCompat are zipped.
      - name: Zip EnvironmentZCompat folder contents
        working-directory: EnvironmentZCompat
        run: |
          rm -f ../environmentz-compat.zip
          zip -r ../environmentz-compat.zip *

      # Create a GitHub Release usin
