name: Create Release Zip

on:
  push:
    tags:
      - 'v*.*.*'  # Adjust the tag pattern as needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository at the pushed tag
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # Change directory to EnvironmentZCompat and zip its contents
      - name: Zip EnvironmentZCompat folder contents
        run: |
          cd EnvironmentZCompat
          zip -r ../environmentz-compat.zip *

      # Create a GitHub Release using the pushed tag
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN
